<a href="https://colab.research.google.com/github/k-seona/lab_python/blob/main/py13_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#데이터 분석 패키지

google colab에는 데이터 분석과 머신 러닝에 필요한 대부분의 패키지들이 이미 설치가 되어 있음.

*numPy : 다차원 배열을 다르는 패키지. 머신 러닝에서 중요하게 사용됨
*pandas: 시리즈, 데이터 프레임을 다루는 페키지 데이터 분석에서 기본으로 사용되는 패키지
* matplotlib: 데이터시각화(그래프)
* seaborn : 데이터 시각화 통게작업


In [ ]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import seaborn as sns

In [ ]:
print('넘피 버전', np.__version__)
print('판다 버전', pd.__version__)
print('멧 버전', mpl.__version__)
print('씨본 버전', sns.__version__)

넘피 버전 1.22.4
판다 버전 1.5.3
멧 버전 3.7.1
씨본 버전 0.12.2


#python `list` class

* 여러개의 값들을 저장할 수 있는 데이터 타입
* 인덱스를 기반으로 값들을 저장, 참조하는 데이터타입.

    *indexiing: 인덱스를 사용해서 원하는 위치의 값을 참조, 변경
    *slicing: `[start, end)` 인덱스 범위의 값들로 이루어진 부분집합을 잘라내는 방법.
* `list + list`:
* `list * int `, `int * list`: 리스트의 원소들을 정수만큼 반복해서 복제
(replicate)

In [ ]:
list1 = [1,2,3,4]
list2 = [10,20,30,40]

In [ ]:
#indexing:
print(list1[0]) #list1의 첫번째 원소
print(list1[3], list1[-1]) # 리스트의 마지막원소

1
4 4


In [ ]:
print(list1[:3]) #list1의 첫번째 원소
print(list1[-3:]) # 리스트의 마지막원소

[1, 2, 3]
[2, 3, 4]


In [ ]:
list1 + list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [ ]:
list1 * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
#list1 , list2에서 같은 인덱스 위치의 원소들끼리 덧셈
[x + y for x,y in zip(list1, list2)]

[11, 22, 33, 44]

In [ ]:
#list1의 모든 원소에 3을 곱함
[3 * x for x in list1]

[3, 6, 9, 12]

#numPy

*배열(ndarray)을 쉽고 빠르게 연산(+, - ,*,//,/,%)을 수행하는 라이브러리
* numPy패키지의 함수 또는 메서드들을 대부분 반복문의 기능을 가지고 있음.
* np.ndarray 클래스 : NumPy패키지에서 기본 타입 클래스. n차원 배열
(n-dimensional array)
    * `ndarray`는 같은 인덱스(위치)에 있는 원소들끼리 연산을 수행

In [ ]:
array1 = np.array([1,2,3]) #python의 list 객체를 numpy의 ndarray 객체로 변환

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
print(array1)# 프린트 함수는 __str__메서드의 리턴값을 출력

[1 2 3]


In [ ]:
array1

array([1, 2, 3])

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print(array2)

[4 5 6]


In [ ]:
#ndarray의 사칙연산 -같은 원소들끼리 연산수행
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


##ndarry클래스의 속성들

In [ ]:
print(array1)
print('ndim:', array1.ndim) #차원(dimesion). 배열의 축(axis)의 개수
print('size',array1.size) # 배열의 크기, 원소 개수
print('shape:',array1.shape) # 배열의 모양, 각 차원에소의 원소 개수
print('dtype:',array1.dtype) # 배열원소의 데이터 타입

[1 2 3]
ndim: 1
size 3
shape: (3,)
dtype: int64


`ndarray`는 한가지 타입의 데이터들만 저장할 수 있는 데이터 타입 - `list`와 다른점

## 2차원 배열

In [ ]:
array_2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [ ]:
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print('ndim:', array_2d.ndim) #차원
print('size:', array_2d.size) #크기
print('shape:', array_2d.shape) #모양
print('dtype:', array_2d.dtype) #데이터타입



ndim: 2
size: 12
shape: (3, 4)
dtype: int64


### 2차원 `ndarray`의 인덱스 사용 방법:
* `array[i][j]` -python list와 같은 사용 방법
* `array[i, j]` -ndarray에서만 사용가능

In [ ]:
array_2d[0,0] #array_2d[0][0]

1

In [ ]:
array_2d[1,2]

7

##`ndarray`인덱스

In [ ]:
#0이상 100이하 범위의 정수,난수 10개를 갖는 ndarray 객체를 생성:
array = np.random.randint(0, 100, size=10)
print(array)

[90 85 32 62 51 98 83 53  7 65]


In [ ]:
#indexing:
print(array[0]) # 첫번째 원소
print(array[-1]) # 마지막 원소

90
65


In [ ]:
#slicing
print(array[0:3]) #첫 3개 원소 자르기
print(array[-3:]) #마지막 3개 원소 자르기


[90 85 32]
[53  7 65]


In [ ]:
print(array[0]) # indexcing -> 아이템(값)
print(array[0:1]) # slicing -> 배열 (ndarray)

90
[90]


### fancy indexcing

* 배열과 비슷한 객체(ndarray, list, tuple, set, ...)를 사용해서 원하는 우너소들을 참조하는 방법
* fancy indexcing의 결과는 ndarray.

In [ ]:
print(array)
print(array[0]) #indexcing /0 아이템/
print(array[[0,2,4]]) #fancy indexcing (인덱스 안에서 리스트 ㄴ ), 인덱스0,2,4번 원소들 찾기
print(array[[0]])  #0번 원소를 갖는 배열 //fancy indexcing->결과는 배열!

[90 85 32 62 51 98 83 53  7 65]
90
[90 32 51]
[90]


### boolean indexcing
*논리값(true/ false)들의 배열 (리스트, 튜플,...)을 사용한 fancy indenxing 방법
*배열에서 조건을 만족하는 원소들로 이루어진 부분집합(ndarray)를 만드는 방법

In [ ]:
print(array)
print(array[[True, False,True, False,True, False,True, False,True, False]])

[90 85 32 62 51 98 83 53  7 65]
[90 32 51 83  7]


In [ ]:
#배열 array의 원소들 중 홀수들만 찾기
array % 2 == 1
print(array % 2)
print(array % 2 == 1)
print(array[array % 2 == 1])

[0 1 0 0 1 0 1 1 1 1]
[False  True False False  True False  True  True  True  True]
[85 51 83 53  7 65]


In [ ]:
#배열 array의 원소들 중에서 50이상인 숫자들의 배열을 찾기:
print(array[array >= 50])

[90 85 62 51 98 83 53 65]


## numPy의 통계함수ㅡ 메서드

* np.function(ndarray) 함수
* np.ndarray.method()메서드

In [ ]:
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [ ]:
#합계:
print(np.sum(array)) #
print(array.sum()) #함수


15
15


In [ ]:
#평균
print(np.mean(array) ) # 함수
print(array.mean ) # 메서드

3.0
<built-in method mean of numpy.ndarray object at 0x7f2a561fe4f0>


* numpy패키지를 사용
* [0 , 100)범위의 난수 10개를 갖는 ndarray를 생성
* 배열에서 최댓값, 최솟값, 평균, 분산(variance), 표준편차( standard deviation) 출력
* 배열의 원소들 중 평균보다 큰 값들로 이루어진 배열을 만들고 출력.


In [73]:
#0이상 100이하 범위의 정수,난수 10개를 갖는 ndarray 객체를 생성:
#분산 (x)2승 / 개수
np.random.seed(1) # 난수들을 생성하는 seed를 설정 -> 항상 같은 난수들을 생성
numbers = np.random.randint(0, 100, size=10)
print(numbers )

print('최댓값', np.max(numbers))
print('최솟값', np.min(numbers))
print('합',np.sum(numbers))
#print('평균',np.mean(numbers))
print('평균', np.average(numbers))
print('분산', np.var(numbers))
print('표준편차', np.std(numbers))
print(numbers[numbers > np.average(numbers)])

[37 12 72  9 75  5 79 64 16  1]
최댓값 79
최솟값 1
합 370
평균 37.0
분산 933.2
표준편차 30.548322376196047
[72 75 79 64]


#2차원 배열에서의 통계 함수, 메서드

In [74]:
# [0, 100] 범위의 정수 난수를 갖는 (3,4) 모양(shape)을 갖는 2차원 ndarrau
np.random.seed(1)
array = np.random.randint(100, size=(3,4))
print(array)

[[37 12 72  9]
 [75  5 79 64]
 [16  1 76 71]]


In [76]:
np.sum(array)  # 배열의 모든 원소들의 합계 // axis=None기본값


517

In [78]:
np.sum(array,axis=0) #세로로 한 줄 0번 axis=0: 2차원 배열에서 첫번째 인덱스가 축 방향으로 계산

array([128,  18, 227, 144])

In [79]:
np.sum(array,axis=1)

array([130, 223, 164])

In [80]:
np.sum(array,axis=1, keepdims=True)

array([[130],
       [223],
       [164]])